### ISSUE TITLE
peerDependency on old filerev

### ISSUE THREAD

**Issue by danielsitnik** [ianwremmel/grunt-filerev-apply#2]
Hi, I'm using this task to replace file paths and it's the only one that's working with my setup (tried with grunt-filerev-replace but no luck).

However, you have a peerDependency on the package.json pointing to a very old version of grunt-filerev. For now I forked your package and removed the dependency and all is working. It would be nice if you could remove the peerDependency (or at least update it to a newer filerev) on your version as well since it's the original one.

Thanks.

**Comment by ianwremmel** [comment]
Fixed in 59de08676aada9370327c2b6576f4bc3ece4d5bf
Released in 0.0.2

**Comment by danielsitnik** [comment]
Thanks, works perfectly.
